// ============================================================
// FILE 3 of 5: KeyData.swift
// Dichotomous identification key
// Based on Davis, Flora of Turkey Vol. 7, pp. 37-42
// ============================================================

import SwiftUI

let keySteps: [KeyStep] = [

    KeyStep(id: "s1",
            question: "How many FERTILE stamens does the flower have?\n(Count only the ones that have pollen)",
            optionA: "2 stamens — the other pair is tiny or missing",
            optionB: "4 stamens — or all reduced/sterile in female flowers",
            nextA: .step("s2"), nextB: .step("s6")),

    KeyStep(id: "s2",
            question: "Look closely at the 2 stamens. Are the CONNECTIVES (the part that joins the 2 pollen sacs) long and lever-like — like a see-saw?",
            optionA: "YES — connectives long and lever-like",
            optionB: "NO — connectives very short, not lever-like",
            nextA: .plant(42), nextB: .step("s3")),

    KeyStep(id: "s3",
            question: "Are the leaves EVERGREEN and NARROW like a needle?",
            optionA: "YES — evergreen, narrow leaves; pale blue corolla 8-12 mm; woody shrub",
            optionB: "NO — leaves deciduous or broader",
            nextA: .plant(3), nextB: .step("s4")),

    KeyStep(id: "s4",
            question: "Where are the FLOWER CLUSTERS (verticillasters)?",
            optionA: "In upper LEAF AXILS, widely spaced; leaves coarsely toothed; non-aromatic",
            optionB: "In TERMINAL SPIKES or HEADS; leaf margins entire or slightly toothed; aromatic",
            nextA: .plant(40), nextB: .step("s5")),

    KeyStep(id: "s5",
            question: "Is the plant a WOODY SHRUB with arrow-shaped (hastate) leaves?",
            optionA: "YES — woody shrub; hastate leaves; slender cylindrical spikes",
            optionB: "NO — annual or perennial herb; cuneate-based leaves; head or spike inflorescence",
            nextA: .plant(43), nextB: .plant(41)),

    KeyStep(id: "s6",
            question: "Look at the UPPER LIP of the corolla (top part of the flower). Is it present?",
            optionA: "NO — upper lip absent or very tiny (flower looks 1-lipped)",
            optionB: "YES — upper lip clearly present and well-developed",
            nextA: .step("s7"), nextB: .step("s8")),

    KeyStep(id: "s7",
            question: "Is the inside of the COROLLA TUBE smooth (glabrous)?",
            optionA: "YES — tube smooth inside; lower lip with 5 lobes",
            optionB: "NO — tube usually has a ring of hairs inside; upper lip reduced to 2 small lobes",
            nextA: .plant(2), nextB: .plant(1)),

    KeyStep(id: "s8",
            question: "Examine the HAIRS on the plant carefully. What type are they?",
            optionA: "BRANCHED — dendroid (tree-like), forked, or stellate (star-shaped)",
            optionB: "SIMPLE (unbranched) only, or the plant has NO hairs at all",
            nextA: .step("s9"), nextB: .step("s14")),

    KeyStep(id: "s9",
            question: "How are the flower clusters arranged?",
            optionA: "In PEDUNCULATE SPIKES (on a long stalk); upper calyx lip has an appendage; stamens droop downward",
            optionB: "NOT in pedunculate spikes; calyx without appendage; stamens not drooping",
            nextA: .plant(4), nextB: .step("s10")),

    KeyStep(id: "s10",
            question: "Do the STAMENS stick out clearly beyond the upper lip of the corolla?",
            optionA: "YES — stamens clearly exserted beyond upper lip; corolla resupinate (upside-down)",
            optionB: "NO — stamens do not stick out beyond the upper lip",
            nextA: .plant(35), nextB: .step("s11")),

    KeyStep(id: "s11",
            question: "Is the upper lip of the corolla FALCATE — curved like a sickle or hood?",
            optionA: "YES — upper lip clearly curved or hooded",
            optionB: "NO — upper lip straight or slightly concave",
            nextA: .plant(9), nextB: .step("s12")),

    KeyStep(id: "s12",
            question: "How many CALYX TEETH are there? What are the hairs like INSIDE the calyx throat?",
            optionA: "5 teeth; calyx throat smooth (glabrous) or weakly hairy",
            optionB: "5-10(-30) teeth; calyx throat has stiff long white hairs",
            nextA: .plant(19), nextB: .step("s13")),

    KeyStep(id: "s13",
            question: "Are the STAMENS hidden (included) inside the corolla tube?",
            optionA: "YES — stamens hidden inside tube; calyx not widened above",
            optionB: "NO — stamens visible; calyx tube widens into a flat star-like toothed limb",
            nextA: .plant(17), nextB: .plant(16)),

    KeyStep(id: "s14",
            question: "Is the FRUITING CALYX greatly enlarged and papery/membranous with broad spreading lobes?",
            optionA: "YES — fruiting calyx greatly enlarged, papery, with broad spreading lobes",
            optionB: "NO — fruiting calyx may enlarge a little but is not papery with broad lobes",
            nextA: .step("s15"), nextB: .step("s17")),

    KeyStep(id: "s15",
            question: "What colour are the LEAVES and COROLLA?",
            optionA: "Leaves woolly; corolla upper lip YELLOW, lower lip orange",
            optionB: "Leaves smooth (glabrous); corolla white, pink, or violet",
            nextA: .plant(8), nextB: .step("s16")),

    KeyStep(id: "s16",
            question: "Is the plant a SHRUB with violet UPSIDE-DOWN (resupinate) corollas?",
            optionA: "YES — shrub; violet resupinate corollas; bracteoles herbaceous",
            optionB: "NO — annual with white/pinkish non-resupinate corollas; bracteoles spiny",
            nextA: .plant(25), nextB: .plant(15)),

    KeyStep(id: "s17",
            question: "How many VEINS or RIBS does the CALYX TUBE have?",
            optionA: "15 or more veins; upper (posterior) stamens LONGER than lower (anterior)",
            optionB: "5-14 veins; lower (anterior) stamens LONGER than upper, or all stamens equal",
            nextA: .step("s18"), nextB: .step("s21")),

    KeyStep(id: "s18",
            question: "Do the CALYX SINUSES (gaps between calyx teeth) have a thickened fold at the base?",
            optionA: "YES — thickened fold present; middle lobe of upper calyx lip clearly broader than side lobes",
            optionB: "NO — calyx sinuses without a thickened fold; lobes similar in width",
            nextA: .step("s19"), nextB: .step("s20")),

    KeyStep(id: "s19",
            question: "Does the UPPER LIP of the corolla have 2 internal longitudinal folds inside?",
            optionA: "YES — 2 internal folds; bracteoles prominently veined and aristate-dentate; annuals or perennials",
            optionB: "NO — no internal folds; bracteoles aristate or acuminate; perennials",
            nextA: .plant(24), nextB: .plant(23)),

    KeyStep(id: "s20",
            question: "Are the flower clusters 2-6-flowered, one-sided (secund), in upper leaf axils? Does the plant spread by stolons (runners)?",
            optionA: "YES — 2-6 flowered, one-sided, plant spreads by stolons",
            optionB: "NO — 6+ flowered; NOT in leaf axils; plant not stoloniferous",
            nextA: .plant(22), nextB: .plant(21)),

    KeyStep(id: "s21",
            question: "Is the COROLLA TUBE long, slender, and S-shaped (sigmoid)?",
            optionA: "YES — long slender S-shaped tube; calyx lips entire; upper calyx has a small flap",
            optionB: "NO — corolla tube not like that; calyx without a flap",
            nextA: .plant(6), nextB: .step("s22")),

    KeyStep(id: "s22",
            question: "Is the upper lip of the corolla FALCATE — curved like a sickle or hood?",
            optionA: "YES — upper lip clearly falcate (curved)",
            optionB: "NO — upper lip straight or slightly concave",
            nextA: .step("s23"), nextB: .step("s29")),

    KeyStep(id: "s23",
            question: "Is the calyx CLEARLY 2-LIPPED (bilabiate)?",
            optionA: "YES — calyx clearly 2-lipped",
            optionB: "NO — calyx not or indistinctly 2-lipped",
            nextA: .step("s24"), nextB: .step("s25")),

    KeyStep(id: "s24",
            question: "Are flower clusters in DENSE TERMINAL SPIKES with bracts hiding the calyces?",
            optionA: "YES — dense terminal spikes; bracts hide calyces; flowers violet or creamy-white; upper lip hairy",
            optionB: "NO — clusters distant; bracts do NOT hide calyces; flowers pinkish; upper lip very hairy/tomentose",
            nextA: .plant(27), nextB: .plant(11)),

    KeyStep(id: "s25",
            question: "Do the NUTLETS (small fruits) have TUFTS OF HAIR at the tip?",
            optionA: "YES — nutlets have hair tufts at the apex",
            optionB: "NO — nutlets are smooth (glabrous)",
            nextA: .step("s26"), nextB: .step("s27")),

    KeyStep(id: "s26",
            question: "How big is the corolla and what do the leaves look like?",
            optionA: "Corolla 5-12 mm, pinkish-white; leaves digitately divided or subentire",
            optionB: "Corolla 18-40 mm, yellow or whitish; leaves pinnate, lobed, or subentire",
            nextA: .plant(14), nextB: .plant(8)),

    KeyStep(id: "s27",
            question: "Are the THECAE (pollen sacs) smooth? Is the corolla yellow? Does the plant spread by runners?",
            optionA: "YES — smooth thecae; yellow corolla; plant stoloniferous (spreads by runners)",
            optionB: "NO — thecae hairy; corolla white, cream, pink, or purple; not stoloniferous",
            nextA: .plant(12), nextB: .step("s28")),

    KeyStep(id: "s28",
            question: "Are the BRACTEOLES SPINY?",
            optionA: "YES — bracteoles spiny; lower lip of corolla with 2 blunt conical appendages; annuals",
            optionB: "NO — bracteoles not spiny; lower lip with very reduced lateral lobes; annuals or perennials",
            nextA: .plant(13), nextB: .plant(10)),

    KeyStep(id: "s29",
            question: "Do the STAMENS stick out clearly beyond the upper lip of the corolla?",
            optionA: "YES — stamens clearly exserted beyond the upper lip",
            optionB: "NO — stamens do not stick out beyond the upper lip",
            nextA: .step("s30"), nextB: .step("s39")),

    KeyStep(id: "s30",
            question: "Is the calyx CLEARLY 2-LIPPED with lower teeth markedly different from the upper?",
            optionA: "YES — clearly 2-lipped; lower teeth very different from upper",
            optionB: "NO — calyx not or indistinctly 2-lipped; upper and lower teeth/lobes similar",
            nextA: .step("s31"), nextB: .step("s35")),

    KeyStep(id: "s31",
            question: "Is the plant an ANNUAL or short-lived perennial? Do the stamens droop (declinate)?",
            optionA: "YES — annual or short-lived perennial; stamens declinate (droop downward)",
            optionB: "NO — shrub or woody-based perennial; stamens not drooping",
            nextA: .step("s32"), nextB: .step("s33")),

    KeyStep(id: "s32",
            question: "Is the calyx BENT BACK (deflexed) in fruit? Is the upper calyx lip broadly circular?",
            optionA: "YES — calyx deflexed in fruit; upper lip broadly circular; inflorescence of racemes",
            optionB: "NO — calyx not deflexed; upper lip not broadly circular; inflorescence a spike",
            nextA: .plant(45), nextB: .plant(44)),

    KeyStep(id: "s33",
            question: "Is the calyx tube FLATTENED from top to bottom (dorsally compressed) with 2 fringed flanges on the sides?",
            optionA: "YES — calyx tube dorsally compressed with 2 ciliolate flanges",
            optionB: "NO — calyx tube not dorsally flattened; no flanges",
            nextA: .step("s34"), nextB: .plant(36)),

    KeyStep(id: "s34",
            question: "What is the INFLORESCENCE TYPE?",
            optionA: "SPICATE (a spike); calyx 13-veined; leaves conduplicate (folded lengthwise)",
            optionB: "CAPITATE (a head); calyx 20-22-veined; leaves subtriquetrious (3-sided)",
            nextA: .plant(38), nextB: .plant(37)),

    KeyStep(id: "s35",
            question: "Is the inflorescence in PANICLES or CORYMBS with prominent overlapping bracts hiding the calyces?",
            optionA: "YES — panicles or corymbs; prominent imbricate bracts usually hiding calyces",
            optionB: "NO — bracts inconspicuous; not hiding calyces",
            nextA: .plant(28), nextB: .step("s36")),

    KeyStep(id: "s36",
            question: "Does the corolla have 4 NEARLY EQUAL LOBES? Does the plant grow in DAMP places with creeping rhizomes?",
            optionA: "YES — 4 subequal lobes; damp habitat; rhizomes root at nodes",
            optionB: "NO — 5 unequal lobes; dry places; no creeping rhizomes",
            nextA: .plant(39), nextB: .step("s37")),

    KeyStep(id: "s37",
            question: "Are the leaves OVATE to SUBORBICULAR? Is the corolla resupinate (upside-down)? Are the thecae parallel?",
            optionA: "YES — leaves ovate to suborbicular; corolla resupinate; thecae parallel",
            optionB: "NO — leaves linear to linear-lanceolate; corolla not resupinate; thecae divergent",
            nextA: .plant(35), nextB: .step("s38")),

    KeyStep(id: "s38",
            question: "Is the calyx tubular (6-8 mm) with thickened folds at the base of the sinuses?",
            optionA: "YES — tubular, 6-8 mm; thickened folds at sinus bases; corolla violet-blue",
            optionB: "NO — ovate-campanulate, 3-4(-5) mm; no thickened folds; corolla white",
            nextA: .plant(26), nextB: .plant(30)),

    KeyStep(id: "s39",
            question: "Does the CALYX THROAT have a BEARD — a ring of stiff, thick white hairs?",
            optionA: "YES — calyx throat has a beard of stiff thick white hairs",
            optionB: "NO — calyx throat smooth or with only a few weak hairs",
            nextA: .step("s40"), nextB: .step("s52")),

    KeyStep(id: "s40",
            question: "Does the corolla have 4 NEARLY EQUAL LOBES? Does the plant grow in DAMP places with rhizomes?",
            optionA: "YES — 4 subequal lobes; damp places; rhizomes rooting at nodes",
            optionB: "NO — 5 unequal lobes (2 upper, 3 lower); dry places; procumbent or erect",
            nextA: .plant(39), nextB: .step("s41")),

    KeyStep(id: "s41",
            question: "Is the calyx dorsally COMPRESSED with 2 lateral fringed (ciliolate) flanges?",
            optionA: "YES — calyx compressed; 2 ciliolate flanges",
            optionB: "NO — calyx not dorsally flattened; no flanges",
            nextA: .step("s42"), nextB: .step("s43")),

    KeyStep(id: "s42",
            question: "What is the INFLORESCENCE TYPE?",
            optionA: "SPICATE (spike); calyx 13-veined; leaves conduplicate",
            optionB: "CAPITATE (head); calyx 20-22-veined; leaves triquetrious",
            nextA: .plant(38), nextB: .plant(37)),

    KeyStep(id: "s43",
            question: "Is the inflorescence in PANICLES or CORYMBS with prominent overlapping bracts hiding the calyces?",
            optionA: "YES — panicles or corymbs; prominent overlapping bracts hiding calyces",
            optionB: "NO — bracts inconspicuous; not hiding calyces",
            nextA: .plant(28), nextB: .step("s44")),

    KeyStep(id: "s44",
            question: "Do ALL parts of the plant have LONG, STURDY HAIRS? Do the calyces have 10-20(-30) ribs?",
            optionA: "YES — long sturdy hairs throughout; calyces 10-20(-30)-ribbed",
            optionB: "NO — hairs short, crisp, or antrorse/retrorse; calyces 5-13(-15)-veined",
            nextA: .step("s45"), nextB: .step("s46")),

    KeyStep(id: "s45",
            question: "Are the stamens INSIDE (included in) the corolla tube? Is the calyx NOT widened above the tube?",
            optionA: "YES — stamens inside tube; calyx not widened above",
            optionB: "NO — stamens NOT inside tube; calyx tube widens into a flat toothed limb",
            nextA: .plant(17), nextB: .plant(16)),

    KeyStep(id: "s46",
            question: "Are the LOWER CALYX TEETH long and awl-shaped (subulate) AND prominently fringed with hairs? Are leaves basally ciliate?",
            optionA: "YES — lower teeth long-subulate, prominently ciliate; leaves usually basally ciliate",
            optionB: "NO — lower teeth shorter; leaves usually without basal cilia",
            nextA: .plant(36), nextB: .step("s47")),

    KeyStep(id: "s47",
            question: "Is the CALYX TUBE strongly CURVED or gibbous (humped/swollen) below?",
            optionA: "YES — calyx tube strongly curved or gibbous (humped) below",
            optionB: "NO — calyx tube roughly straight",
            nextA: .step("s48"), nextB: .step("s49")),

    KeyStep(id: "s48",
            question: "Is the calyx tube strongly CURVED (not just humped) with long hair-fringed teeth? Are they perennials?",
            optionA: "YES — tube strongly curved; teeth long-ciliate; perennials",
            optionB: "NO — tube gibbous (humped) below, constricted above; annuals or perennials",
            nextA: .plant(32), nextB: .plant(33)),

    KeyStep(id: "s49",
            question: "Are the LOWER CALYX LIP TEETH clearly fringed with hairs (ciliate)? Are the leaves petiolate (on stalks)?",
            optionA: "YES — lower lip teeth clearly ciliate; leaves petiolate",
            optionB: "NO — lower lip teeth not or scarcely ciliate; leaves petiolate or subsessile",
            nextA: .plant(31), nextB: .step("s50")),

    KeyStep(id: "s50",
            question: "Are leaves SUBSESSILE and CUNEATE (wedge-shaped), folded (conduplicate) when young? Calyx 10-13-veined?",
            optionA: "YES — subsessile, cuneate, conduplicate when young; calyx 10-13-veined; stamens divergent",
            optionB: "NO — leaves petiolate, flat or with revolute margins; calyx 5-13(-15)-veined; stamens parallel",
            nextA: .plant(30), nextB: .step("s51")),

    KeyStep(id: "s51",
            question: "Is the calyx 1.5-6 mm with 13-15 veins, with the corolla tube INSIDE (not sticking out of) the calyx?",
            optionA: "YES — calyx 1.5-6 mm, 13-15-veined; corolla tube inside calyx; inflorescence often cymose",
            optionB: "NO — calyx 6+ mm, 5-10-veined; corolla tube sticks out; not cymose",
            nextA: .plant(34), nextB: .plant(19)),

    KeyStep(id: "s52",
            question: "Are the BRACTEOLES awl-shaped, spiny, and bent back (deflexed)? Is the upper calyx lip rigid with a single 4-8 mm spine?",
            optionA: "YES — awl-shaped, spiny, deflexed bracteoles; upper calyx lip rigid with 1 large spine",
            optionB: "NO — bracteoles herbaceous (leaf-like), erect or spreading; upper calyx lip not like that",
            nextA: .plant(15), nextB: .step("s53")),

    KeyStep(id: "s53",
            question: "Is the calyx CLEARLY 2-LIPPED (bilabiate)?",
            optionA: "YES — calyx clearly 2-lipped",
            optionB: "NO — calyx not or indistinctly 2-lipped",
            nextA: .step("s54"), nextB: .step("s58")),

    KeyStep(id: "s54",
            question: "Is the plant a SHRUB (nearly glabrous) with fleshy BLACK fruit and flowers in terminal leafy racemes?",
            optionA: "YES — shrub; nearly glabrous; terminal leafy racemes; fleshy black fruit",
            optionB: "NO — herbs or suffruticose (woody at base); prominent hairs; fruit dry",
            nextA: .plant(5), nextB: .step("s55")),

    KeyStep(id: "s55",
            question: "Are the flowers in UPPER LEAF AXILS (not in bracts that are different from leaves)?",
            optionA: "YES — flowers in upper leaf axils",
            optionB: "NO — flowers in axils of BRACTS that are different from the leaves",
            nextA: .step("s56"), nextB: .step("s57")),

    KeyStep(id: "s56",
            question: "How large is the COROLLA?",
            optionA: "About 35 mm (large!); pedicels 6-8 mm",
            optionB: "About 8-15 mm (smaller); pedicels about 3 mm",
            nextA: .plant(7), nextB: .plant(20)),

    KeyStep(id: "s57",
            question: "Are the leaves SUBSESSILE and cuneate, conduplicate when young, glandular-punctate? Calyx 10-13-veined?",
            optionA: "YES — subsessile, cuneate, conduplicate, glandular; calyx 10-13-veined",
            optionB: "NO — leaves petiolate, ovate to oblong; calyx 5-10-veined",
            nextA: .plant(30), nextB: .plant(18)),

    KeyStep(id: "s58",
            question: "Is the inflorescence in PANICLES or CORYMBS with prominent overlapping bracts hiding the calyces?",
            optionA: "YES — panicles or corymbs; prominent imbricate bracts hiding calyces",
            optionB: "NO — bracts inconspicuous",
            nextA: .plant(28), nextB: .step("s59")),

    KeyStep(id: "s59",
            question: "Does the corolla have 4 NEARLY EQUAL LOBES? Does the plant grow in DAMP places with rhizomes rooting at nodes?",
            optionA: "YES — 4 subequal lobes; damp places; rhizomes rooting at nodes",
            optionB: "NO — 5 unequal lobes; dry places",
            nextA: .plant(39), nextB: .step("s60")),

    KeyStep(id: "s60",
            question: "Do ALL parts of the plant have LONG STURDY HAIRS? Do the calyces have 10-20 ribs?",
            optionA: "YES — long sturdy hairs throughout; calyces 10-20-ribbed",
            optionB: "NO — hairs shorter; calyces fewer-ribbed",
            nextA: .plant(17), nextB: .plant(19)),
]
